single-char-binding-names-threshold = 3
too-large-for-stack = 256
cognitive-complexity-threshold = 12
array-size-threshold = 262144 #2^18
enum-variant-size-threshold = 128
too-many-arguments-threshold = 4
literal-representation-threshold = 16
too-many-lines-threshold = 64
trivial-copy-size-limit = 2
max-include-file-size = 262144
type-complexity-threshold = 32
max-trait-bounds = 1
vec-box-size-threshold = 1024
